/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Server
 */
public class addproducts extends javax.swing.JFrame {

    /**
     * Creates new form addproducts
     */
    public addproducts() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Code = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        SellingAmount = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();
        Supplier = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel37 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        PurchaseAmount = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        NameOfProducts = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        Date = new com.toedter.calendar.JDateChooser();
        NetIncome = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        kButton6 = new com.k33ptoo.components.KButton();
        jLabel27 = new javax.swing.JLabel();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton7 = new com.k33ptoo.components.KButton();
        kButton5 = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Rectangle 30.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel21MousePressed(evt);
            }
        });
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Rectangle 31.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel22MousePressed(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        Code.setBorder(null);
        jPanel1.add(Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 160, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 160, 10));

        jLabel32.setText("Code : ");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 100, 20));

        jLabel33.setText("Date : ");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 100, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 160, 10));

        SellingAmount.setBorder(null);
        jPanel1.add(SellingAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 160, 30));

        jLabel35.setText("Selling amount");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 100, 20));

        kButton2.setText("Update");
        kButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(238, 77, 116));
        kButton2.setkEndColor(new java.awt.Color(238, 77, 116));
        kButton2.setkHoverEndColor(new java.awt.Color(238, 77, 116));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(238, 77, 116));
        kButton2.setkPressedColor(new java.awt.Color(238, 77, 116));
        kButton2.setkSelectedColor(new java.awt.Color(238, 77, 116));
        kButton2.setkStartColor(new java.awt.Color(238, 77, 116));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 100, 40));

        Supplier.setBorder(null);
        jPanel1.add(Supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 160, 30));

        jLabel36.setText("Supplier : ");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 100, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 160, 10));

        jLabel37.setText("Quantity :");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 100, 20));

        Quantity.setBorder(null);
        jPanel1.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 160, 30));

        PurchaseAmount.setBorder(null);
        jPanel1.add(PurchaseAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 160, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 160, 10));

        jLabel34.setText("Purchase amount :");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 100, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 160, 10));

        NameOfProducts.setBorder(null);
        jPanel1.add(NameOfProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 160, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel30.setText("ADD PRODUCTS");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 190, 20));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 160, 10));

        jLabel31.setText("Name of Product");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 100, 20));

        Date.setBackground(new java.awt.Color(255, 255, 255));
        Date.setDateFormatString("yyyy-MM-dd");
        Date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 160, 30));

        NetIncome.setBorder(null);
        jPanel1.add(NetIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 160, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 160, 10));

        jLabel38.setText("Net income :");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 100, 20));

        kButton6.setText("Submit");
        kButton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kButton6.setkBackGroundColor(new java.awt.Color(0, 204, 102));
        kButton6.setkEndColor(new java.awt.Color(0, 204, 102));
        kButton6.setkHoverEndColor(new java.awt.Color(0, 204, 102));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton6.setkHoverStartColor(new java.awt.Color(0, 204, 102));
        kButton6.setkPressedColor(new java.awt.Color(0, 204, 102));
        kButton6.setkSelectedColor(new java.awt.Color(0, 204, 102));
        kButton6.setkStartColor(new java.awt.Color(0, 204, 102));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 100, 40));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("MENU");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 80, 20));

        kButton3.setBackground(new java.awt.Color(255, 204, 204));
        kButton3.setForeground(new java.awt.Color(0, 0, 0));
        kButton3.setText("Add Products");
        kButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton3.setkBackGroundColor(new java.awt.Color(255, 204, 204));
        kButton3.setkEndColor(new java.awt.Color(255, 204, 204));
        kButton3.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverColor(new java.awt.Color(255, 204, 204));
        kButton3.setkHoverEndColor(new java.awt.Color(255, 204, 204));
        kButton3.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverStartColor(new java.awt.Color(255, 204, 204));
        kButton3.setkPressedColor(new java.awt.Color(255, 204, 204));
        kButton3.setkSelectedColor(new java.awt.Color(255, 204, 204));
        kButton3.setkStartColor(new java.awt.Color(255, 204, 204));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 110, 40));

        kButton4.setBackground(new java.awt.Color(255, 255, 255));
        kButton4.setForeground(new java.awt.Color(0, 0, 0));
        kButton4.setText("View Expenses");
        kButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton4.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton4.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton4.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton4.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton4.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton4.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton4.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton4.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton4.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 40));

        kButton1.setBackground(new java.awt.Color(255, 255, 255));
        kButton1.setForeground(new java.awt.Color(0, 0, 0));
        kButton1.setText("View Sales");
        kButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton1.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton1.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 204, 204));
        kButton1.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 204, 204));
        kButton1.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton1.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 110, 40));

        kButton7.setBackground(new java.awt.Color(255, 255, 255));
        kButton7.setForeground(new java.awt.Color(0, 0, 0));
        kButton7.setText("View Stocks");
        kButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton7.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton7.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton7.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton7.setkHoverEndColor(new java.awt.Color(255, 204, 204));
        kButton7.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton7.setkHoverStartColor(new java.awt.Color(255, 204, 204));
        kButton7.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton7.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton7.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, 40));

        kButton5.setBackground(new java.awt.Color(255, 255, 255));
        kButton5.setForeground(new java.awt.Color(0, 0, 0));
        kButton5.setText("View Suppliers");
        kButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton5.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton5.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton5.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton5.setkHoverEndColor(new java.awt.Color(255, 204, 204));
        kButton5.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton5.setkHoverStartColor(new java.awt.Color(255, 204, 204));
        kButton5.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton5.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton5.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Rectangle 12 (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel21MousePressed

    private void jLabel22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MousePressed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel22MousePressed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        String code = Code.getText();
        String NameOfProduct = NameOfProducts.getText();
        String PurchaseAm = PurchaseAmount.getText();
        String SellAmount = SellingAmount.getText();
        String Quan = Quantity.getText();
        java.sql.Date date = new java.sql.Date(Date.getDate().getTime());
        String Supp = Supplier.getText();
        String NetInc = NetIncome.getText();
        if (Code.getText().equals("") || NameOfProducts.getText().equals("")
                || PurchaseAmount.getText().equals("") || SellingAmount.getText().equals("")
                || Quantity.getText().equals("") || Supplier.getText().equals("") || NetIncome.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Something is messing please double check");
        } else {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://192.168.1.187:3306/inventory", "root", "");
                Statement stm = con.createStatement();
                stm.execute("UPDATE `products` SET `Code`='" + code + "',`NameOfProduct`='" + NameOfProduct + "',"
                        + "`PurchaseAmount`='" + PurchaseAm + "',`SellingAmount`='" + SellAmount + "',`Quantity`='" + Quan + "',"
                        + "`Date`='" + date + "',`Supplier`='" + Supp + "',`NetIncome`='" + NetInc + "' WHERE code=" + code + "");
                JOptionPane.showMessageDialog(null, NameOfProduct + " Update");
            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "DATABASE Connection Field.");
                ///System.out.println(ex);
            }
        }
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        String code = Code.getText();
        String NameOfProduct = NameOfProducts.getText();
        String PurchaseAm = PurchaseAmount.getText();
        String SellAmount = SellingAmount.getText();
        String Quan = Quantity.getText();
        java.sql.Date date = new java.sql.Date(Date.getDate().getTime());
        String Supp = Supplier.getText();
        String NetInc = NetIncome.getText();
        if (Code.getText().equals("") || NameOfProducts.getText().equals("")
                || PurchaseAmount.getText().equals("") || SellingAmount.getText().equals("")
                || Quantity.getText().equals("") || Supplier.getText().equals("") || NetIncome.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Something is messing please double check");
        } else {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://192.168.1.187:3306/inventory", "root", "");
                Statement stm = con.createStatement();
                stm.executeUpdate("INSERT INTO `products`(`Code`, `NameOfProduct`, `PurchaseAmount`, `SellingAmount`, "
                        + "`Quantity`, `Date`, `Supplier`, `NetIncome`) "
                        + "VALUES ('" + code + "','" + NameOfProduct + "','" + PurchaseAm + "','" + SellAmount + "','" + Quan + "','" + date + "',"
                        + "'" + Supp + "','" + NetInc + "')");
                JOptionPane.showMessageDialog(null, NameOfProduct + " Saved");
            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "DATABASE Connection Field.");
                ///System.out.println(ex);
            }
        }
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        new addproducts().setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        new expenses().setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        new sales().setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton7ActionPerformed
        new stocks().setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton7ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        new suppliers().setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addproducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addproducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addproducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addproducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addproducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Code;
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JTextField NameOfProducts;
    private javax.swing.JTextField NetIncome;
    private javax.swing.JTextField PurchaseAmount;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField SellingAmount;
    private javax.swing.JTextField Supplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton6;
    private com.k33ptoo.components.KButton kButton7;
    // End of variables declaration//GEN-END:variables
}
