/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Server
 */
public class cashier_dash extends javax.swing.JFrame {

    /**
     * Creates new form cashier_dash
     */
    public cashier_dash() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory", "root", "");
            String sql = "SELECT Code,NameOfProduct,SellingAmount,NetIncome AS NTA,Quantity FROM `products`;";
            //  SupplierList.setForeground(Color.black);
            PreparedStatement pstm = con.prepareStatement(sql);
            ResultSet rs = pstm.executeQuery();
            ListOfProducts.setModel(DbUtils.resultSetToTableModel(rs));
            try {
            } catch (Exception e) {
                System.out.println(e);
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton7 = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();
        jLabel30 = new javax.swing.JLabel();
        NameOfProduct = new javax.swing.JTextField();
        Code = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        kButton6 = new com.k33ptoo.components.KButton();
        jLabel7 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        Discount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AmountRecieved = new javax.swing.JTextField();
        Change = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        Date = new com.toedter.calendar.JDateChooser();
        jScrollPane19 = new javax.swing.JScrollPane();
        ListOfProducts = new javax.swing.JTable();
        AvQuantity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        AvQuantity1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        net = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("MENU");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 80, 20));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Rectangle 30.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel21MousePressed(evt);
            }
        });
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Rectangle 31.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel22MousePressed(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, -1));

        kButton3.setBackground(new java.awt.Color(255, 204, 204));
        kButton3.setForeground(new java.awt.Color(0, 0, 0));
        kButton3.setText("Add Sales");
        kButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton3.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton3.setkEndColor(new java.awt.Color(255, 204, 204));
        kButton3.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverColor(new java.awt.Color(255, 204, 204));
        kButton3.setkHoverEndColor(new java.awt.Color(255, 204, 204));
        kButton3.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverStartColor(new java.awt.Color(255, 204, 204));
        kButton3.setkPressedColor(new java.awt.Color(255, 204, 204));
        kButton3.setkSelectedColor(new java.awt.Color(255, 204, 204));
        kButton3.setkStartColor(new java.awt.Color(255, 204, 204));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, 40));

        kButton4.setBackground(new java.awt.Color(255, 255, 255));
        kButton4.setForeground(new java.awt.Color(0, 0, 0));
        kButton4.setText("Expenses");
        kButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton4.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton4.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton4.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton4.setkHoverEndColor(new java.awt.Color(255, 204, 204));
        kButton4.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton4.setkHoverStartColor(new java.awt.Color(255, 204, 204));
        kButton4.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton4.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton4.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 40));

        kButton1.setBackground(new java.awt.Color(255, 255, 255));
        kButton1.setForeground(new java.awt.Color(0, 0, 0));
        kButton1.setText("View Sales");
        kButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton1.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton1.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton1.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton1.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 120, 40));

        kButton7.setBackground(new java.awt.Color(255, 204, 204));
        kButton7.setForeground(new java.awt.Color(0, 0, 0));
        kButton7.setText("View Stocks");
        kButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton7.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton7.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton7.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton7.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton7.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton7.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton7.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton7.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton7.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Rectangle 12 (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 390));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("MENU");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 80, 20));

        jLabel3.setText("Name of Product : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        kButton2.setText("Calculate");
        kButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(238, 77, 116));
        kButton2.setkEndColor(new java.awt.Color(238, 77, 116));
        kButton2.setkHoverEndColor(new java.awt.Color(238, 77, 116));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(238, 77, 116));
        kButton2.setkPressedColor(new java.awt.Color(238, 77, 116));
        kButton2.setkSelectedColor(new java.awt.Color(238, 77, 116));
        kButton2.setkStartColor(new java.awt.Color(238, 77, 116));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 80, 40));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel30.setText("CASHIER DASCHBOARD");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 280, 20));

        NameOfProduct.setBorder(null);
        jPanel1.add(NameOfProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 170, 30));

        Code.setBorder(null);
        jPanel1.add(Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 170, 30));

        jLabel4.setText("Code :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        Quantity.setBorder(null);
        Quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QuantityKeyReleased(evt);
            }
        });
        jPanel1.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 170, 30));

        jLabel5.setText("Quantity");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jLabel6.setText("Date : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 170, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 170, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 170, 10));

        kButton6.setText("Submit");
        kButton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kButton6.setkBackGroundColor(new java.awt.Color(0, 204, 102));
        kButton6.setkEndColor(new java.awt.Color(0, 204, 102));
        kButton6.setkHoverEndColor(new java.awt.Color(0, 204, 102));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton6.setkHoverStartColor(new java.awt.Color(0, 204, 102));
        kButton6.setkPressedColor(new java.awt.Color(0, 204, 102));
        kButton6.setkSelectedColor(new java.awt.Color(0, 204, 102));
        kButton6.setkStartColor(new java.awt.Color(0, 204, 102));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 80, 40));

        jLabel7.setText("Amount : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        Amount.setBorder(null);
        jPanel1.add(Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 170, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 170, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 170, 10));

        Discount.setText("0");
        Discount.setBorder(null);
        jPanel1.add(Discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 170, 30));

        jLabel8.setText("Discount :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        AmountRecieved.setBorder(null);
        jPanel1.add(AmountRecieved, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, 30));

        Change.setText("0");
        Change.setBorder(null);
        jPanel1.add(Change, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 170, 30));

        jLabel9.setText("Change :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 170, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 170, 10));

        jLabel10.setText("Amount recieved :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        Date.setDateFormatString("yyyy-MM-dd");
        Date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 170, 30));

        ListOfProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ListOfProducts.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        ListOfProducts.setAutoscrolls(false);
        ListOfProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ListOfProducts.setRowHeight(25);
        ListOfProducts.setSelectionBackground(new java.awt.Color(255, 51, 51));
        ListOfProducts.setSurrendersFocusOnKeystroke(true);
        ListOfProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListOfProductsMousePressed(evt);
            }
        });
        jScrollPane19.setViewportView(ListOfProducts);

        jPanel1.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 290, 340));

        AvQuantity.setBorder(null);
        jPanel1.add(AvQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 170, 30));

        jLabel11.setText("Available Quantity :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 170, 10));

        AvQuantity1.setBorder(null);
        jPanel1.add(AvQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 170, 30));

        jLabel12.setText("Total Quantity Available");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 170, 10));

        net.setBorder(null);
        jPanel1.add(net, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 170, 30));

        jLabel13.setText("NTA : ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 170, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel21MousePressed

    private void jLabel22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MousePressed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel22MousePressed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        new cashier_dash().setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        new cashier_exp().setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        String productName = NameOfProduct.getText();
        DecimalFormat jk = new DecimalFormat("###,###.##");
        try {
            NumberFormat usFormat = NumberFormat.getNumberInstance(java.util.Locale.US);
            double amount = usFormat.parse(Amount.getText()).doubleValue();
            double quantity = usFormat.parse(Quantity.getText()).doubleValue();
            double discount = usFormat.parse(Discount.getText()).doubleValue();
            double amountRecieved = usFormat.parse(AmountRecieved.getText()).doubleValue();

            //Amount*Quantity-Discount
            double ADQ = amount * quantity - discount;
            //AMR = AmountRecieved - ADQ
            double AMR = amountRecieved - ADQ;

            String x = jk.format(AMR);
            Change.setText("" + x + ".00");

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        String code = Code.getText();
        String productName = NameOfProduct.getText();
        String amount = Amount.getText();
        String discount = Discount.getText();
        String quantity = Quantity.getText();
        java.sql.Date date = new java.sql.Date(Date.getDate().getTime());
        String amountrecieved = AmountRecieved.getText();
        String change = Change.getText();
        String NetAmount = net.getText();
        if (Code.getText().equals("") || NameOfProduct.getText().equals("") || Amount.getText().equals("") || Discount.getText().equals("")
                || Quantity.getText().equals("") || date.equals("") || AmountRecieved.getText().equals("") || Change.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Something is messing please double check");
        } else {

            try {
                DecimalFormat jk = new DecimalFormat("###,### - PCS");
                try {

                    NumberFormat usFormat = NumberFormat.getNumberInstance(java.util.Locale.US);
                    double quan = usFormat.parse(Quantity.getText()).doubleValue();
                    double AvQuant = usFormat.parse(AvQuantity.getText()).doubleValue();
                    double TotalQua = AvQuant - quan;
                    String x = jk.format(TotalQua);
                    AvQuantity1.setText("" + x);
                    //MYSQL Driver
                    Class.forName("com.mysql.jdbc.Driver");
                    //database Connection 
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory", "root", "");
                    Statement stm = con.createStatement();
                    //This code is to insert into Sales record 
                    stm.execute("INSERT INTO `sales`(`Code`, `NameOfProduct`, `Amount`, `Discount`, `Quantity`, `Date`, "
                            + "`AmountRecieved`, `ChangeAmount`,`NetAmount`) VALUES ('" + code + "','" + productName + "','" + amount + "','" + discount + "',"
                            + "'" + quantity + "','" + date + "','" + amountrecieved + "','" + change + "','" + NetAmount + "')");
                    //This code to update the quantity of the products
                    stm.executeUpdate("UPDATE `products` SET `Quantity` = '" + TotalQua + "' WHERE `products`.`Code` = '" + code + "'");
                    JOptionPane.showMessageDialog(null, productName + " Saved");
                } catch (ClassNotFoundException | SQLException ex) {
                    JOptionPane.showMessageDialog(null, "DATABASE Connection Field. or It's already saved.");
                    System.out.println(ex);
                }
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        new cashier_sales().setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton7ActionPerformed
        new cashier_stocks().setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton7ActionPerformed

    private void ListOfProductsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListOfProductsMousePressed
        TableModel modell = ListOfProducts.getModel();
        int i = ListOfProducts.getSelectedRow();
        Code.setText(modell.getValueAt(i, 0).toString());
        NameOfProduct.setText(modell.getValueAt(i, 1).toString());
        Amount.setText(modell.getValueAt(i, 2).toString());
        net.setText(modell.getValueAt(i, 3).toString());
        AvQuantity.setText(modell.getValueAt(i, 4).toString());

    }//GEN-LAST:event_ListOfProductsMousePressed

    private void QuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityKeyReleased
        try {
            DecimalFormat jk = new DecimalFormat("###,### - PCS");
            NumberFormat usFormat = NumberFormat.getNumberInstance(java.util.Locale.US);
            double quan = usFormat.parse(Quantity.getText()).doubleValue();
            double AvQuant = usFormat.parse(AvQuantity.getText()).doubleValue();
            double TotalQua = AvQuant - quan;
            String x = jk.format(TotalQua);
            AvQuantity1.setText("" + x);
        } catch (ParseException ex) {
            Logger.getLogger(cashier_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_QuantityKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashier_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashier_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashier_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashier_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashier_dash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount;
    private javax.swing.JTextField AmountRecieved;
    private javax.swing.JTextField AvQuantity;
    private javax.swing.JTextField AvQuantity1;
    private javax.swing.JTextField Change;
    private javax.swing.JTextField Code;
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JTextField Discount;
    private javax.swing.JTable ListOfProducts;
    private javax.swing.JTextField NameOfProduct;
    private javax.swing.JTextField Quantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton6;
    private com.k33ptoo.components.KButton kButton7;
    private javax.swing.JTextField net;
    // End of variables declaration//GEN-END:variables
}
